export const FETCH_STUDENTS = 'FETCH_STUDENTS'
export const FETCH_STUDENTS_ERROR = 'FETCH_STUDENTS_ERROR'

export const DELETE_STUDENT = 'DELETE_STUDENT'
export const DELETE_STUDENT_ERROR = 'DELETE_STUDENT_ERROR'

export const CREATE_STUDENT = 'CREATE_STUDENT'
export const CREATE_STUDENT_ERROR = 'CREATE_STUDENT_ERROR'

export const UPDATE_STUDENT = 'UPDATE_STUDENT'
export const UPDATE_STUDENT_ERROR = 'UPDATE_STUDENT_ERROR'

export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR'

export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS'
export const LOG_OUT_ERROR = 'LOG_OUT_ERROR'